[package]
name = "oxidris-evaluator"
version.workspace = true
edition.workspace = true

[dependencies]
arrayvec.workspace = true
oxidris-engine.workspace = true
serde.workspace = true

[lints]
workspace = true
