[package]
name = "oxidris-training"
version.workspace = true
edition.workspace = true

[dependencies]
oxidris-engine.workspace = true
oxidris-evaluator.workspace = true
oxidris-stats.workspace = true
rand.workspace = true
rand_distr.workspace = true

[lints]
workspace = true
